#define _ACTIONS

AbstractSyntaxTreeNode *DefaultSemanticAction(void *scopeStack, Stack *semanticStack);
void AssignActions(Grammar *g);

void GenerateArithmeticExpression(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateAddition(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateSubtraction(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateIntegerLiteral(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateFloatLiteral(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateStringLiteral(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateAssignment(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateMult(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateDivision(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateDeclaration(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateSymbol(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateAdditionAssignment(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateReturn(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateIf(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateFor(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateIncrement(void *codeGenerator, AbstractSyntaxTreeNode *astNode);
void GenerateStatements(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateExpression(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateCall(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateReference(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateDereference(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateLT(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateGT(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateGE(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateLE(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateEEQ(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateNEQ(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateLSHIFT(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateRSHIFT(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateMod(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateAnd(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateXor(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateNeg(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateIndexing(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateLogNot(void *generator, AbstractSyntaxTreeNode *astRoot);
void GenerateStructAccess(void *generator, AbstractSyntaxTreeNode *astRoot);

void AnalyzeAddition(AbstractSyntaxTreeNode **astNode);
void AnalyzeStructAccess(AbstractSyntaxTreeNode **astNode);
void AnalyzeSubtraction(AbstractSyntaxTreeNode **astNode);
// void AnalyzeIntegerLiteral(AbstractSyntaxTreeNode **astNode);
// void AnalyzeFloatLiteral(AbstractSyntaxTreeNode **astNode);
// void AnalyzeStringLiteral(AbstractSyntaxTreeNode **astNode);
// void AnalyzeAssignment(AbstractSyntaxTreeNode **astNode);
// void AnalyzeMult(AbstractSyntaxTreeNode **astNode);
// void AnalyzeDivision(AbstractSyntaxTreeNode **astNode);
// void AnalyzeDeclaration(AbstractSyntaxTreeNode **astNode);
// void AnalyzeSymbol(AbstractSyntaxTreeNode **astNode);
// void AnalyzeAdditionAssignment(AbstractSyntaxTreeNode **astNode);
// void AnalyzeReturn(AbstractSyntaxTreeNode **astNode);
// void AnalyzeIf(AbstractSyntaxTreeNode **astNode);
// void AnalyzeIncrement(AbstractSyntaxTreeNode **astNode);
// void AnalyzeStatements(AbstractSyntaxTreeNode **astNode);
// void AnalyzeExpression(AbstractSyntaxTreeNode **astNode);
// void AnalyzeCall(AbstractSyntaxTreeNode **astNode);
void AnalyzeReference(AbstractSyntaxTreeNode **astNode);
void AnalyzeDereference(AbstractSyntaxTreeNode **astNode);
// void AnalyzeLT(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeGT(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeGE(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeLE(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeEEQ(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeNEQ(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeLSHIFT(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeRSHIFT(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeMod(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeAnd(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeNeg(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeIndexing(AbstractSyntaxTreeNode ***astNode);
// void AnalyzeLogNot(AbstractSyntaxTreeNode ***astNode);